### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by lionhurt** [xiaokaike/vue-color#106]
Hi, 
Thank you for great effort

~~I think we need to clear button to completely remove the color if not needed~~
it's very easy to make one .. Thank you so much

**Comment by linx4200** [comment]
What do you mean by removing the color if not needed ?
There are some color presets you don't need in the components?

**Comment by lionhurt** [comment]
in my case i use this control in some elements on the page, sometime you need to remove the color from the elements like iview/element color picker https://cl.ly/1t0s2w2H221f

**Comment by linx4200** [comment]
In my opinion, this kind of button should be implemented outside `vue-color` components. I guess the clear button you mentioned is to reset the color to default, so, you can do this:

```html
<div>
  <color-picker v-model="colors" />
  <button @click="onClick">Clear</button>
</div>
```

```js
const defaultColors = '#f00';
export default {
  data () {
    return {
      colors: defaultColors
    }
  },
  methods: {
    onClick() {
      this.colors = defaultColors
    }
  }
}
```

**Comment by terryw3316** [comment]
I think a clear button would be useful, for example I need to allow for a null choice, if a colour is not required, as it stands this doesn't seem to be allowed?

**Comment by linx4200** [comment]
@terryw3316 

Yes, right now it's not allowed to pass an empty object or `null` as color to the `vue-color` component.

Maybe you can set a default color like `#fff` ? 

And I still think it would be better that clear button is  implemented outside `vue-color` components. Because the components we provided mimic the color pickers provided by Photoshop, Sketch, etc, which don't have a clear button.

In the next big release 3.0, it is possible to customize color picker using some basic color components such as 'Hue' and 'Saturation'. Then you can totally add a clear button to your own color picker.

**Comment by linx4200** [comment]
@terryw3316  Glad that you find a work around and thanks for your feedback.  😃
