### ISSUE TITLE
Slider pIcker default color issue

### ISSUE THREAD

**Issue by MikeLP** [xiaokaike/vue-color#39]
Slider can't move when default hex color is #101010

**Comment by ehrig** [comment]
I encounter the same issue. The slider can not be moved when the initial hex color value is set to any color that has the same or nearby RGB values. For example:

#000000
#424242
#cccccc
#d6d6d6

etc. (you get the picture)

The slider works when you first move the upper color picker and then the slider, but it is more of a workaround to circumvent this bug and just bad UX. End users are very confused by this.

When I pick a close by default hex value such as '#cccccd' the slider moves but in steps. If I just move away far enough from the color that is causing the issue, at some point, it works. This confirms my guess from the beginning that the slider is buggy when the default color has the same/nearby RGB values.

**Comment by cassioscabral** [comment]
That is a weird behavior, I never worked on the slider and don't have enough time at the moment to work on that. If anyone could debug this and open a PR, feel free to clone and check this file (https://github.com/xiaokaike/vue-color/blob/master/src/components/Slider.vue). I can check the PR and test myself if it's working to accept it. 

We are having some issues with tinycolor  lib, the conversions in tinycolor are converted to RGB and values other than that it ends up losing some precision in the conversion. This could be related with that, but I'm not sure.

**Comment by mirshko** [comment]
@MikeLP do you mean the Hue slider? We are having issues where it cannot be moved with the default value of #ffffff I believe this is due to the code not taking into account the ability to slide to a different hue as white doesn't have 'hues' per say. @xiaokaike We are having issues with this as well on bug https://github.com/buildbetterCTAs/app.responsivectabuilder.com/issues/75 Please address this sooner rather than later.

**Comment by mirshko** [comment]
@xiaokaike ?

**Comment by linx4200** [comment]
Fixed. Please update to the latest version.
